import type { Plugin } from 'vite';
import fs from 'node:fs';
import path from 'node:path';
import { init, parse } from 'es-module-lexer';

/** SvelteKit 支持的 HTTP 方法 */
const HTTP_METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'] as const;
type HttpMethod = (typeof HTTP_METHODS)[number];

/** API 定义文件名 */
const API_NAME = '-api.server.ts';
/** 生成文件标记，防止覆盖用户文件 */
const GENERATED_MARKER = '// @generated by vite-plugin-api-routes — DO NOT EDIT\n';

const ESLINT_IGNORE_ALL = '/* eslint-disable */\n';

/** 生成文件名 */
const SERVER_FILE = '+server.ts';
const REMOTE_FILE = 'api.remote.ts';
const GITIGNORE_FILE = '.gitignore';

/** API 路由根目录 */
const API_ROUTES_DIR = 'src/routes/api';

const GITIGNORE_CONTENT = `/${SERVER_FILE}\n/${REMOTE_FILE}\n`;

/** 日志前缀 */
const LOG_PREFIX = '[api-routes]';

interface MethodInfo {
	method: HttpMethod;
	hasSchema: boolean;
	hasDescription: boolean;
	customName?: string;
}

interface EndpointInfo {
	filePath: string;
	routePath: string;
	methods: MethodInfo[];
}

/**
 * 解析 `-api.server.ts` 文件，检测导出的 `z<METHOD>` 和 `<METHOD>` 对。
 *
 * 识别以下模式：
 *   export const zGET = z.object(...)
 *   export async function GET(...)
 *   export function GET(...)
 *   export const GET = ...
 */
async function parseApiExports(filePath: string): Promise<MethodInfo[]> {
	const content = await fs.promises.readFile(filePath, 'utf-8');
	await init;
	const [_, exports] = parse(content);
	const exportNames = new Set(exports.map((exp) => exp.n));

	const methods: MethodInfo[] = [];
	for (const method of HTTP_METHODS) {
		const handlerExists = exportNames.has(method);
		if (!handlerExists) continue;
		const schemaExists = exportNames.has(`z${method}`);
		let customName: string | undefined;
		if (exportNames.has(`n${method}`)) {
			const re = new RegExp(`export\\s+(?:const|let|var)\\s+n${method}\\s*=\\s*(['"])([^'"]*?)\\1`);
			const match = content.match(re);
			if (match) customName = match[2];
		}
		const hasDescription = exportNames.has(`d${method}`);
		methods.push({ method, hasSchema: schemaExists, hasDescription, customName });
	}
	return methods;
}

/** 判断方法是否使用请求体（而非查询参数） */
function usesBody(method: HttpMethod): boolean {
	return method === 'POST' || method === 'PUT' || method === 'PATCH';
}

/**
 * 生成 `+server.ts` 内容。
 *
 * GET/DELETE — 通过 `parseSearchParams` 解析查询参数。
 * POST/PUT/PATCH — 通过 `parseBody` 解析请求体。
 */
function generateServerFile(apiFileName: string, methods: MethodInfo[]): string {
	const lines: string[] = [];

	// 构建导入项：将处理函数别名为 _GET、_POST 等以避免命名冲突
	const apiImportItems: string[] = [];
	for (const { method, hasSchema } of methods) {
		apiImportItems.push(`${method} as _${method}`);
		if (hasSchema) apiImportItems.push(`z${method}`);
	}

	// 仅导入实际需要的解析辅助函数
	const needsBody = methods.some((m) => m.hasSchema && usesBody(m.method));
	const needsParams = methods.some((m) => m.hasSchema && !usesBody(m.method));
	const parseImports: string[] = ['success'];
	if (needsBody) parseImports.push('parseBody');
	if (needsParams) parseImports.push('parseSearchParams');

	lines.push(`import type { RequestHandler } from './$types';`);
	lines.push(`import { ${parseImports.join(', ')} } from '$api/common.server';`);
	lines.push(`import { ${apiImportItems.join(', ')} } from './${apiFileName}';`);

	for (const { method, hasSchema } of methods) {
		lines.push('');
		if (hasSchema) {
			const parser = usesBody(method) ? 'parseBody' : 'parseSearchParams';
			lines.push(`export const ${method}: RequestHandler = async () => {`);
			lines.push(`\tconst params = await ${parser}(z${method});`);
			lines.push(`\tconst data = await _${method}(params);`);
			lines.push(`\treturn success({ data });`);
			lines.push(`};`);
		} else {
			lines.push(`export const ${method}: RequestHandler = async () => {`);
			lines.push(`\tconst data = await _${method}();`);
			lines.push(`\treturn success({ data });`);
			lines.push(`};`);
		}
	}

	return GENERATED_MARKER + ESLINT_IGNORE_ALL + lines.join('\n') + '\n';
}

/** 从文件路径计算路由路径标识（如 v1_test） */
function getRoutePath(filePath: string): string {
	const rel = path.relative(path.resolve(API_ROUTES_DIR), path.dirname(filePath));
	return rel.split(path.sep).filter(Boolean).join('_');
}

/**
 * 生成 `api.remote.ts` 内容（SvelteKit 远程函数）。
 *
 * GET 使用 `query`，其他变更方法使用 `command`。
 * 导出名默认为 `{routePath}_{method}`，可通过 `nMETHOD` 覆盖。
 */
function generateRemoteFile(apiFileName: string, methods: MethodInfo[], routePath: string): string {
	methods = methods.filter((m) => m.customName !== '');
	const needsQuery = methods.some((m) => m.method === 'GET');
	const needsCommand = methods.some((m) => m.method !== 'GET');

	const appImports: string[] = [];
	if (needsQuery) appImports.push('query');
	if (needsCommand) appImports.push('command');

	const apiImportItems: string[] = [];
	for (const { method, hasSchema } of methods) {
		apiImportItems.push(method);
		if (hasSchema) apiImportItems.push(`z${method}`);
	}

	let code = GENERATED_MARKER;
	code += ESLINT_IGNORE_ALL;
	code += `import { ${appImports.join(', ')} } from '$app/server';\n`;
	code += `import { ${apiImportItems.join(', ')} } from './${apiFileName}';\n`;

	for (const { method, hasSchema, customName } of methods) {
		const fn = method === 'GET' ? 'query' : 'command';
		const exportName = customName ?? `${routePath}_${method.toLowerCase()}`;
		code += '\n';
		if (hasSchema) {
			code += `export const ${exportName} = ${fn}(z${method}, ${method});\n`;
		} else {
			code += `export const ${exportName} = ${fn}(${method});\n`;
		}
	}

	return code;
}

/**
 * 删除指定路径的生成文件（仅当文件以 GENERATED_MARKER 开头时）。
 */
async function removeGeneratedFile(filePath: string) {
	if (!fs.existsSync(filePath)) return;
	try {
		const content = await fs.promises.readFile(filePath, 'utf-8');
		if (content.startsWith(GENERATED_MARKER)) {
			await fs.promises.unlink(filePath);
			console.log(`${LOG_PREFIX} 已删除生成文件 ${path.relative(process.cwd(), filePath)}`);
		}
	} catch (err) {
		console.error(`${LOG_PREFIX} 删除文件失败 ${filePath}:`, err);
	}
}

/**
 * 处理单个 `-api.server.ts` 文件：生成 `+server.ts` 和 `api.remote.ts`。
 * 如果没有导出任何 METHOD，则删除已有的生成文件。
 */
async function processApiFile(filePath: string): Promise<EndpointInfo | undefined> {
	const dir = path.dirname(filePath);
	const basename = path.basename(filePath);

	if (basename !== API_NAME) return undefined;

	const apiFileName = basename.replace(/\.ts$/, '');

	let methods: MethodInfo[];
	try {
		methods = await parseApiExports(filePath);
	} catch (err) {
		console.error(`${LOG_PREFIX} 解析失败 ${filePath}:`, err);
		return undefined;
	}

	const serverPath = path.join(dir, SERVER_FILE);
	const remotePath = path.join(dir, REMOTE_FILE);
	const gitignorePath = path.join(dir, GITIGNORE_FILE);

	// 没有导出任何 METHOD 时，删除已有的生成文件
	if (methods.length === 0) {
		await removeGeneratedFile(serverPath);
		await removeGeneratedFile(remotePath);
		return undefined;
	}

	// 避免覆盖非生成文件
	for (const target of [serverPath, remotePath]) {
		if (fs.existsSync(target)) {
			const existing = fs.readFileSync(target, 'utf-8');
			if (!existing.startsWith(GENERATED_MARKER)) {
				console.warn(`${LOG_PREFIX} 跳过 ${path.relative(process.cwd(), target)} — 非生成文件`);
				return undefined;
			}
		}
	}

	let serverContent: string, remoteContent: string;
	try {
		serverContent = generateServerFile(apiFileName, methods);
		remoteContent = generateRemoteFile(apiFileName, methods, getRoutePath(filePath));
	} catch (err) {
		console.error(`${LOG_PREFIX} 生成内容失败 ${filePath}:`, err);
		return undefined;
	}

	// 写入文件
	await writeIfChanged(serverPath, serverContent);
	await writeIfChanged(remotePath, remoteContent);
	await writeIfChanged(gitignorePath, GITIGNORE_CONTENT);
	console.log(`${LOG_PREFIX} 已生成文件 ${path.relative(process.cwd(), filePath)}`);

	const routePath = getRoutePath(filePath);
	return { filePath, routePath, methods };
}

async function writeIfChanged(filePath: string, content: string) {
	try {
		if (fs.existsSync(filePath)) {
			const existing = await fs.promises.readFile(filePath, 'utf-8');
			if (existing === content) return;
		}
		await fs.promises.writeFile(filePath, content, 'utf-8');
	} catch (err) {
		console.error(`${LOG_PREFIX} 写入失败 ${filePath}:`, err);
	}
}

/** 从 routePath 生成 API URL 路径 */
function getApiUrlPath(routePath: string): string {
	return '/api/' + routePath.replace(/_/g, '/');
}

/** 生成 openapi-registry.server.ts 注册表文件 */
async function generateRegistryFile(endpoints: EndpointInfo[]) {
	const apiDir = path.resolve(API_ROUTES_DIR);
	const registryPath = path.join(apiDir, 'openapi-registry.server.ts');

	// 按路径排序
	const sorted = [...endpoints].sort((a, b) => a.routePath.localeCompare(b.routePath));

	const importLines: string[] = [];
	const entryLines: string[] = [];

	for (let fileIdx = 0; fileIdx < sorted.length; fileIdx++) {
		const ep = sorted[fileIdx];
		const prefix = `s${fileIdx}`;

		// 计算相对于 src/routes/api/ 的 import 路径
		const relPath = path.relative(apiDir, ep.filePath).replace(/\.ts$/, '');
		const importPath = './' + relPath.split(path.sep).join('/');

		// 收集该文件的所有 import 项
		const importItems: string[] = [];
		for (const m of ep.methods) {
			if (m.hasSchema) importItems.push(`z${m.method} as ${prefix}_z${m.method}`);
			if (m.hasDescription) importItems.push(`d${m.method} as ${prefix}_d${m.method}`);
		}

		if (importItems.length > 0) {
			importLines.push(`import { ${importItems.join(', ')} } from '${importPath}';`);
		}

		const apiUrl = getApiUrlPath(ep.routePath);

		for (const m of ep.methods) {
			const operationId = m.customName ?? `${ep.routePath}_${m.method.toLowerCase()}`;
			const descriptionValue = m.hasDescription ? `${prefix}_d${m.method}` : 'undefined';
			const schemaValue = m.hasSchema ? `${prefix}_z${m.method}` : 'undefined';

			entryLines.push(`  {`);
			entryLines.push(`    path: '${apiUrl}',`);
			entryLines.push(`    method: '${m.method}',`);
			entryLines.push(`    operationId: '${operationId}',`);
			entryLines.push(`    description: ${descriptionValue},`);
			entryLines.push(`    schema: ${schemaValue},`);
			entryLines.push(`    usesBody: ${usesBody(m.method)},`);
			entryLines.push(`  },`);
		}
	}

	const lines: string[] = [];
	lines.push(GENERATED_MARKER.trimEnd());
	lines.push(ESLINT_IGNORE_ALL.trimEnd());
	lines.push(`import type z from 'zod';`);
	for (const imp of importLines) lines.push(imp);
	lines.push('');
	lines.push('export interface ApiEndpoint {');
	lines.push('  path: string;');
	lines.push('  method: string;');
	lines.push('  operationId: string;');
	lines.push('  description?: string;');
	lines.push('  schema?: z.ZodType;');
	lines.push('  usesBody: boolean;');
	lines.push('}');
	lines.push('');
	lines.push('export const endpoints: ApiEndpoint[] = [');
	for (const entry of entryLines) lines.push(entry);
	lines.push('];');
	lines.push('');

	await writeIfChanged(registryPath, lines.join('\n'));

	// 管理 src/routes/api/.gitignore
	const apiGitignorePath = path.join(apiDir, GITIGNORE_FILE);
	const apiGitignoreEntry = '/openapi-registry.server.ts\n';
	await writeIfChanged(apiGitignorePath, apiGitignoreEntry);

	console.log(`${LOG_PREFIX} 已生成注册表 ${path.relative(process.cwd(), registryPath)}`);
}

async function scanAll() {
	const watchDir = path.resolve(API_ROUTES_DIR);
	if (!fs.existsSync(watchDir)) return;

	const files: string[] = [];
	// 同步收集所有文件，异步处理
	function walkDir(dir: string) {
		for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
			const full = path.join(dir, entry.name);
			if (entry.isDirectory()) {
				walkDir(full);
			} else if (entry.isFile() && path.basename(entry.name) === API_NAME) {
				files.push(full);
			}
		}
	}
	walkDir(watchDir);

	// 并发处理文件，错误隔离
	const results = await Promise.all(files.map((file) => processApiFile(file)));
	const endpoints = results.filter((ep): ep is EndpointInfo => ep !== undefined);

	// 生成注册表
	await generateRegistryFile(endpoints);
}

/**
 * API 路由生成插件.
 * 改变传统的API定义模式.
 *
 * - 定义`-api.server.ts`文件，导出HTTP方法，支持zod schema，描述，自定义名称。
 * - 自动生成`+server.ts`,`api.remote.ts`文件
 */
export function apiRoutes(): Plugin {
	return {
		name: 'vite-plugin-api-routes',
		configResolved(config) {
			// 仅开发模式在配置阶段扫描；构建模式由 buildStart 负责，避免并发冲突
			if (config.command === 'serve') {
				console.log(`${LOG_PREFIX} 正在扫描 API 文件...`);
				scanAll().catch((err) => console.error(`${LOG_PREFIX} 扫描出错:`, err));
			}
		},
		configureServer(server) {
			const resolvedApiDir = path.resolve(API_ROUTES_DIR);

			// 开发模式下监听文件变更
			const handleFile = async (filePath: string) => {
				if (path.basename(filePath) === API_NAME && filePath.startsWith(resolvedApiDir)) {
					console.log(`${LOG_PREFIX} 检测到文件变更: ${path.relative(process.cwd(), filePath)}`);
					await scanAll();
				}
			};
			const handleUnlink = async (filePath: string) => {
				if (path.basename(filePath) === API_NAME && filePath.startsWith(resolvedApiDir)) {
					console.log(`${LOG_PREFIX} 文件已删除: ${path.relative(process.cwd(), filePath)}`);
					const dir = path.dirname(filePath);
					const serverPath = path.join(dir, SERVER_FILE);
					const remotePath = path.join(dir, REMOTE_FILE);

					await removeGeneratedFile(serverPath);
					await removeGeneratedFile(remotePath);
					await scanAll();
				}
			};

			console.log(`${LOG_PREFIX} 正在监听文件变更...`);

			server.watcher.on('change', handleFile);
			server.watcher.on('add', handleFile);
			server.watcher.on('unlink', handleUnlink);
		},
	};
}

if (process.argv[2] === 'generate') {
	console.log(`${LOG_PREFIX} CLI 模式：扫描 API 文件...`);
	scanAll()
		.then(() => console.log(`${LOG_PREFIX} 生成完成`))
		.catch((err) => {
			console.error(`${LOG_PREFIX} 扫描出错:`, err);
			process.exit(1);
		});
}
